
DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS GAME;
DROP TABLE IF EXISTS BOX;


CREATE TABLE PLAYER (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   username VARCHAR(200) NOT NULL UNIQUE,
   password VARCHAR(200),
   is_connected BIT,
   color BIT
);

CREATE TABLE GAME (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   id_player1 INTEGER,
   id_player2 INTEGER,
   playing BIT,
   FOREIGN KEY (id_player1) REFERENCES PLAYER(id),
   FOREIGN KEY (id_player2) REFERENCES PLAYER(id)
);

CREATE TABLE BOX (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  id_player INTEGER,
  id_game INTEGER,
  X_POSITION INTEGER,
  Y_POSITION INTEGER,
  FOREIGN KEY (id_player) REFERENCES PLAYER(id),
  FOREIGN KEY (id_game) REFERENCES GAME(id)
);
