
DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS GAME;
DROP TABLE IF EXISTS BOX;


CREATE TABLE PLAYER (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   username VARCHAR(200) NOT NULL UNIQUE,
   password VARCHAR(200),
   is_playing BIT,
   is_connected BIT,
   color BIT
);

CREATE TABLE GAME (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   id_player1_id INTEGER,
   id_player2_id INTEGER,
   playing INTEGER,
   FOREIGN KEY (id_player1_id) REFERENCES PLAYER(id),
   FOREIGN KEY (id_player2_id) REFERENCES PLAYER(id)
);

CREATE TABLE BOX (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  id_player_id INTEGER,
  id_game_id INTEGER,
  X_POSITION INTEGER,
  Y_POSITION INTEGER,
  FOREIGN KEY (id_player_id) REFERENCES PLAYER(id),
  FOREIGN KEY (id_game_id) REFERENCES GAME(id)
);
